clear
seriese_task;
COS_COF_3 = Series_COS_List(:,1);
COS_COF_2 = Series_COS_List(:,2);
COS_COF_1 = Series_COS_List(:,3);
COS_COF_0 = Series_COS_List(:,4);
DIVIDE_SIGN = (repelem('_',73))';
[COS_COF_SIGN_0,COS_COF_EXP_0,COS_COF_FRAC_0] = COF_TRANSFER(COS_COF_0,35,5);
COS_COF_0_BIN = [COS_COF_SIGN_0,DIVIDE_SIGN,COS_COF_EXP_0,DIVIDE_SIGN,COS_COF_FRAC_0];
%verify frac
%factor = 2^35;
% frac_quan = frac.*2^35;
%frac_bin  = dec2bin(q,frac_quan);
% frac_bin_2  = frac_bin(1:end,2:end);
% frac_bin_2 == COS_COF_FRAC_0;
[COS_COF_SIGN_1,COS_COF_EXP_1,COS_COF_FRAC_1] = COF_TRANSFER(COS_COF_1,35,5);
COS_COF_1_BIN = [COS_COF_SIGN_1,DIVIDE_SIGN,COS_COF_EXP_1,DIVIDE_SIGN,COS_COF_FRAC_1];
[COS_COF_SIGN_2,COS_COF_EXP_2,COS_COF_FRAC_2] = COF_TRANSFER(COS_COF_2,39,5);
COS_COF_2_BIN = [COS_COF_SIGN_2,DIVIDE_SIGN,COS_COF_EXP_2,DIVIDE_SIGN,COS_COF_FRAC_2];
[COS_COF_SIGN_3,COS_COF_EXP_3,COS_COF_FRAC_3] = COF_TRANSFER(COS_COF_3,39,5);
COS_COF_3_BIN = [COS_COF_SIGN_3,DIVIDE_SIGN,COS_COF_EXP_3,DIVIDE_SIGN,COS_COF_FRAC_3];
COS_ALL_COF = [COS_COF_0_BIN,DIVIDE_SIGN,COS_COF_1_BIN,DIVIDE_SIGN,COS_COF_2_BIN,DIVIDE_SIGN,COS_COF_3_BIN];
COS_cof_file = fopen("COS_COF.coe","w");
for j=1:73
    fprintf(COS_cof_file,"%s\r\n",COS_ALL_COF(j,:));
end