clear
seriese_task;
SIN_COF_3 = Series_SIN_List(:,1);
SIN_COF_2 = Series_SIN_List(:,2);
SIN_COF_1 = Series_SIN_List(:,3);
SIN_COF_0 = Series_SIN_List(:,4);
DIVIDE_SIGN = (repelem('_',73))';
[SIN_COF_SIGN_0,SIN_COF_EXP_0,SIN_COF_FRAC_0] = COF_TRANSFER(SIN_COF_0,35,5);
SIN_COF_0_BIN = [SIN_COF_SIGN_0,DIVIDE_SIGN,SIN_COF_EXP_0,DIVIDE_SIGN,SIN_COF_FRAC_0];
%verify frac
%factor = 2^35;
% frac_quan = frac.*2^35;
%frac_bin  = dec2bin(q,frac_quan);
% frac_bin_2  = frac_bin(1:end,2:end);
% frac_bin_2 == SIN_COF_FRAC_0;
[SIN_COF_SIGN_1,SIN_COF_EXP_1,SIN_COF_FRAC_1] = COF_TRANSFER(SIN_COF_1,35,5);
SIN_COF_1_BIN = [SIN_COF_SIGN_1,DIVIDE_SIGN,SIN_COF_EXP_1,DIVIDE_SIGN,SIN_COF_FRAC_1];
[SIN_COF_SIGN_2,SIN_COF_EXP_2,SIN_COF_FRAC_2] = COF_TRANSFER(SIN_COF_2,39,5);
SIN_COF_2_BIN = [SIN_COF_SIGN_2,DIVIDE_SIGN,SIN_COF_EXP_2,DIVIDE_SIGN,SIN_COF_FRAC_2];
[SIN_COF_SIGN_3,SIN_COF_EXP_3,SIN_COF_FRAC_3] = COF_TRANSFER(SIN_COF_3,39,5);
SIN_COF_3_BIN = [SIN_COF_SIGN_3,DIVIDE_SIGN,SIN_COF_EXP_3,DIVIDE_SIGN,SIN_COF_FRAC_3];
SIN_ALL_COF = [SIN_COF_0_BIN,DIVIDE_SIGN,SIN_COF_1_BIN,DIVIDE_SIGN,SIN_COF_2_BIN,DIVIDE_SIGN,SIN_COF_3_BIN];
sin_cof_file = fopen("SIN_COF.coe","w");
for j=1:73
    fprintf(sin_cof_file,"%s\r\n",SIN_ALL_COF(j,:));
end
